[project]
name = "myshkin_code_sratchbook"
version = "0.1.0"
description = "Проект-памятка для погружения в Python"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.5.3",
    "matplotlib>=3.10.8",
    "pandas>=3.0.0",
]
